defmodule Stackd.Repo.Migrations.CreateMoviesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:movies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tmdb_id, :bigint, null: false
      add :title, :text, null: false
      add :overview, :text
      add :poster_path, :text
      add :release_date, :date

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:movies, [:tmdb_id], name: "movies_unique_tmdb_id_index")
  end

  def down do
    drop_if_exists unique_index(:movies, [:tmdb_id], name: "movies_unique_tmdb_id_index")

    drop table(:movies)
  end
end
