defmodule Stackd.Repo.Migrations.AddLogTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tv_show_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rating, :bigint
      add :logged_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :notes, :text
      add :is_rewatch, :boolean, null: false, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "tv_show_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tv_show_id,
          references(:tv_shows,
            column: :id,
            name: "tv_show_logs_tv_show_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:tv_show_logs, [:user_id, :tv_show_id, :logged_date],
             name: "tv_show_logs_unique_user_tv_show_date_index"
           )

    create table(:movie_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rating, :bigint
      add :logged_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :notes, :text
      add :is_rewatch, :boolean, null: false, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "movie_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :movie_id,
          references(:movies,
            column: :id,
            name: "movie_logs_movie_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:movie_logs, [:user_id, :movie_id, :logged_date],
             name: "movie_logs_unique_user_movie_date_index"
           )

    create table(:game_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rating, :bigint
      add :logged_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :notes, :text
      add :is_replay, :boolean, null: false, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "game_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :game_id,
          references(:games,
            column: :id,
            name: "game_logs_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:game_logs, [:user_id, :game_id, :logged_date],
             name: "game_logs_unique_user_game_date_index"
           )

    create table(:album_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rating, :bigint
      add :logged_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :notes, :text
      add :is_relisten, :boolean, null: false, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "album_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :album_id,
          references(:albums,
            column: :id,
            name: "album_logs_album_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:album_logs, [:user_id, :album_id, :logged_date],
             name: "album_logs_unique_user_album_date_index"
           )
  end

  def down do
    drop_if_exists unique_index(:album_logs, [:user_id, :album_id, :logged_date],
                     name: "album_logs_unique_user_album_date_index"
                   )

    drop constraint(:album_logs, "album_logs_user_id_fkey")

    drop constraint(:album_logs, "album_logs_album_id_fkey")

    drop table(:album_logs)

    drop_if_exists unique_index(:game_logs, [:user_id, :game_id, :logged_date],
                     name: "game_logs_unique_user_game_date_index"
                   )

    drop constraint(:game_logs, "game_logs_user_id_fkey")

    drop constraint(:game_logs, "game_logs_game_id_fkey")

    drop table(:game_logs)

    drop_if_exists unique_index(:movie_logs, [:user_id, :movie_id, :logged_date],
                     name: "movie_logs_unique_user_movie_date_index"
                   )

    drop constraint(:movie_logs, "movie_logs_user_id_fkey")

    drop constraint(:movie_logs, "movie_logs_movie_id_fkey")

    drop table(:movie_logs)

    drop_if_exists unique_index(:tv_show_logs, [:user_id, :tv_show_id, :logged_date],
                     name: "tv_show_logs_unique_user_tv_show_date_index"
                   )

    drop constraint(:tv_show_logs, "tv_show_logs_user_id_fkey")

    drop constraint(:tv_show_logs, "tv_show_logs_tv_show_id_fkey")

    drop table(:tv_show_logs)
  end
end
