defmodule Stackd.Repo.Migrations.AddRolesAndPermissions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :role, :text, null: false, default: "user"
      add :permissions, {:array, :text}, null: false, default: []
      add :banned_at, :utc_datetime_usec
      add :ban_reason, :text
    end
  end

  def down do
    alter table(:users) do
      remove :ban_reason
      remove :banned_at
      remove :permissions
      remove :role
    end
  end
end
