defmodule Stackd.Repo.Migrations.AddUsernameToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :username, :text, null: false
      add :display_name, :text, null: false
      add :bio, :text
      add :avatar_url, :text
    end
  end

  def down do
    alter table(:users) do
      remove :avatar_url
      remove :bio
      remove :display_name
      remove :username
    end
  end
end
