defmodule Stackd.Repo.Migrations.CreateMediaTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tv_shows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tmdb_id, :bigint, null: false
      add :name, :text, null: false
      add :overview, :text
      add :poster_path, :text
      add :backdrop_path, :text
      add :first_air_date, :date
      add :genres, {:array, :text}, default: []

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tv_shows, [:tmdb_id], name: "tv_shows_unique_tmdb_id_index")

    alter table(:movies) do
      add :backdrop_path, :text
      add :genres, {:array, :text}, default: []
    end

    create table(:games, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rawg_id, :bigint, null: false
      add :name, :text, null: false
      add :description, :text
      add :poster_path, :text
      add :backdrop_path, :text
      add :released, :date
      add :genres, {:array, :text}, default: []

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:games, [:rawg_id], name: "games_unique_rawg_id_index")

    create table(:albums, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :spotify_id, :text, null: false
      add :name, :text, null: false
      add :artist, :text, null: false
      add :poster_path, :text
      add :backdrop_path, :text
      add :release_date, :date
      add :genres, {:array, :text}, default: []

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:albums, [:spotify_id], name: "albums_unique_spotify_id_index")
  end

  def down do
    drop_if_exists unique_index(:albums, [:spotify_id], name: "albums_unique_spotify_id_index")

    drop table(:albums)

    drop_if_exists unique_index(:games, [:rawg_id], name: "games_unique_rawg_id_index")

    drop table(:games)

    alter table(:movies) do
      remove :genres
      remove :backdrop_path
    end

    drop_if_exists unique_index(:tv_shows, [:tmdb_id], name: "tv_shows_unique_tmdb_id_index")

    drop table(:tv_shows)
  end
end
