defmodule Stackd.Repo.Migrations.AddProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :display_name, :text, null: true
      modify :username, :text, null: true
      add :profile_completed_at, :utc_datetime_usec
      add :username_last_changed_at, :utc_datetime_usec
    end

    create unique_index(:users, [:username], name: "users_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    alter table(:users) do
      remove :username_last_changed_at
      remove :profile_completed_at
      modify :username, :text, null: false
      modify :display_name, :text, null: false
    end
  end
end
